apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: arcasuite
resources:
  - ../../base/namespace.yaml
  - ../../../subprojects/arca-flow-k8s/base
  - ../../../subprojects/arca-decision-room-k8s/base
  - ../../../subprojects/arca-hub-k8s/base
  - ../../../subprojects/arca-exchange-k8s/base
  - ../../../subprojects/arca-packs-k8s/base
  - ../../../subprojects/arca-trust-k8s/base
  - ../../../subprojects/arca-studio-k8s/base
  - ../../../subprojects/arca-bench-k8s/base
  - ../../../subprojects/arca-cert-k8s/base
commonLabels:
  app.kubernetes.io/part-of: arca-suite
  app.kubernetes.io/managed-by: arca-platform
  cluster: server01
