apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - ../../../platform/base
labels:
  - pairs:
      app.kubernetes.io/part-of: arca-suite
      app.kubernetes.io/managed-by: arca-platform
      cluster: server01
    includeSelectors: true
    includeTemplates: true
